### ISSUE TITLE
TIFF reading error

### ISSUE THREAD

**Issue by michaelthornton** [shiveshc/whole-brain_DeepDenoising#5]
Hi Shivesh,

I am testing out NIDDL on some in vivo calcium imaging data using the example notebook. When I run the 6th cell (train_X, train_Y, test_X, test_Y, tsize = get_data(model_config) ...) I receive the error below. The timelapses were Prairie-TIFFs from a Bruker microscope that were registered with Normcorre and saved out as individual images into the noisy and gt folders using the ImageJ Bioformats Exporter. ImageJ and finder show these images to be 8-bit Tiffs. I also tried converting them all to 32-bit Tiffs and I get the same error. Thanks for your help. 

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/niddl-env/lib/python3.9/site-packages/tifffile/tifffile.py in ?(self, file, mode, name, offset, size, omexml, _multifile, _useframes, _parent, **is_flags)
   4098         except Exception:
   4099             fh.close()
-> 4100             raise

KeyError: b'\x00\x00'

During handling of the above exception, another exception occurred:

TiffFileError                             Traceback (most recent call last)
/var/folders/wt/fvc8_myx1l75zj65g64j04jr0000gn/T/ipykernel_59147/2690101964.py in ?()
----> 1 train_X, train_Y, test_X, test_Y, tsize = get_data(model_config)
      2 print(train_X.shape)
      3 print(train_Y.shape)
      4 print(test_X.shape)

~/Desktop/Analysis/NIDDL/train.py in ?(model_config)
     21     ## load data
     22     all_gt_img_data = []
     23     all_noisy_data = []
     24     for paths in model_config.data:
---> 25         all_gt_img_data, all_noisy_data = load_data(paths, 
     26                                                     all_gt_img_data,
     27                                                     all_noisy_data,
     28                                                     model_config.max_proj)

~/Desktop/Analysis/NIDDL/utils.py in ?(data_path, all_gt_img_data, all_noisy_data, max_proj)
     14     stack_list = os.listdir(gt_img_path)
     15 
     16     for stack in stack_list:
     17         if os.path.isfile(os.path.join(gt_img_path, stack)):
---> 18             curr_img_gt = tifffile.imread(os.path.join(gt_img_path, stack))
     19             curr_img_noisy = tifffile.imread(os.path.join(noisy_img_path, stack))
     20             # curr_img_gt = cv2.imread(os.path.join(gt_img_path, stack), -1)
     21             # curr_img_noisy = cv2.imread(os.path.join(noisy_img_path, stack), -1)

~/anaconda3/envs/niddl-env/lib/python3.9/site-packages/tifffile/tifffile.py in ?(files, aszarr, key, series, level, squeeze, maxworkers, mode, name, offset, size, pattern, axesorder, categories, imread, sort, container, chunkshape, dtype, axestiled, ioworkers, chunkmode, fillvalue, zattrs, multiscales, omexml, out, out_inplace, _multifile, _useframes, **kwargs)
   1058 
   1059         if isinstance(files, str) or not isinstance(
   1060             files, collections.abc.Sequence
   1061         ):
-> 1062             with TiffFile(
   1063                 files,
   1064                 mode=mode,
   1065                 name=name,

~/anaconda3/envs/niddl-env/lib/python3.9/site-packages/tifffile/tifffile.py in ?(self, file, mode, name, offset, size, omexml, _multifile, _useframes, _parent, **is_flags)
   4096                 self.pages.useframes = True
   4097 
   4098         except Exception:
   4099             fh.close()
-> 4100             raise

TiffFileError: not a TIFF file b'\x00\x00\x00\x01'

**Comment by shiveshc** [comment]
Hi Michael

Thanks for trying out NIDDL. Hope you find it useful.

Would it be possible for you to provide
1) Data folder structure - what are the files/folders within gt_imgs and
noisy_imgs folders. Is each image a single zplane image or a multi z-plane
tif file.
2) An example noisy and gt image

Best
Shivesh

**Comment by michaelthornton** [comment]
They are from single plane time series, no z information (mode = 2D, depth = 1). 

The file structure looks like the attached images. Nothing else is in the parent folder except for gt_imgs and noisy_imgs. Btw the example data works fine on my machine. thanks. 

<img width="453" alt="Screenshot 2023-12-23 at 8 35 10 AM" src="https://github.com/shiveshc/NIDDL/assets/31776175/fc7f6fea-73bf-4eec-8a1a-60e35aba5d70">
<img width="451" alt="Screenshot 2023-12-23 at 8 35 31 AM" src="https://github.com/shiveshc/NIDDL/assets/31776175/3fe4758c-5bfa-4de4-9ed7-9137d60e29cd">

**Comment by shiveshc** [comment]
Thanks for providing the folder structure. The folder structure looks correct.

The error seems to be tifffile being unable to read image. To debug, I would suggest just reading couple of images using tifffile. E.g. running `tifffile.imread(/gt_imgs/img_490.tif)` and see if images can be read without errors. If not, the issue would be that images are not saved correctly in tif format.

Could you also try 
`skimage.io.imread(/gt_imgs/img_490.tif)` and see if the image can be read

Let me know how it goes.

Shivesh

**Comment by michaelthornton** [comment]
<img width="1290" alt="Screenshot 2023-12-24 at 6 00 51 PM" src="https://github.com/shiveshc/NIDDL/assets/31776175/ffd7e233-303f-4d69-92dc-986348ac3a2b">
I tried a few images from both noisy and gt datasets and they seem to load fine. Thank you

**Comment by shiveshc** [comment]
Thanks a lot for checking that images can be read by tifffile.

This is really confusing, but few other suggestions I have are - 
1. The `data` field provided in `train_config` is the folder path immediately up of `gt_imgs` and `noisy_imgs` folders. e.g. in your case it could be
```
train_config = {
    'data': ['/Training'],
    'arch': 'unet_fixed',
    'epochs': 2,
    'mode': '2D',
    'depth': 1,
    'loss': 'l2'
}
```
2. Could you check that there are only tifffiles present in gt_imgs and noisy_imgs folder `[f for f in os.listdir('/Training/gt_imgs') if not f.endswith('tif')]`. I am wondering if there are some other type of files inadvertently present in the folder

Best
Shivesh

**Comment by shiveshc** [comment]
Hi Michael
Were you able to debug the issue of loading images?
Shivesh

**Comment by michaelthornton** [comment]
Hi Shivesh,

Sorry for the delay over the holidays. It was a silly problem with the mac finder's hidden ds.store files in the directories. 

I ran [f for f in os.listdir('/Training/gt_imgs') if not f.endswith('tif')] and it returned "ds.store". so I cd'd into the directory and ran: 

% sudo find . -name ‘.DS_Store’ -type f -delete

and the code ran fine. I am getting some promising results albeit with higher loss than your example data (fig.). I will try to train on l1 loss function but any other suggestions for parameter-tweaking would be helpful. These images are relatively small fields (512x512; 0.241 um / pixel) and are very noisy. 

Cheers and thank you for the great tool. 

<img width="632" alt="Screenshot 2024-01-08 at 9 51 32 AM" src="https://github.com/shiveshc/NIDDL/assets/31776175/b886f5ed-93e0-4884-96c5-084c98516406">

**Comment by shiveshc** [comment]
Good to know the issue got resolved.

Regarding the training loss, I would suggest trying out lower learning rate and more number of epochs.
Other than that you can try l1 loss function as you suggested and different cnn architectures. Currently there are 4 that you can try ['unet', 'unet_fixed', 'hourglass_wores', 'hourglass_wres'].

All the best.
